version: 2

defaults: &defaults
  docker:
    - image: circleci/node:10.16.2
  working_directory: ~/repo

jobs:
  setup:
    <<: *defaults
    steps:
      - checkout
      - restore_cache:
          key: dependencies-{{ checksum "package-lock.json" }}
      - run: npm install
      - save_cache:
          key: dependencies-{{ checksum "package-lock.json" }}
          paths:
            - node_modules
      - persist_to_workspace:
          root: ~/repo
          paths:
            - ./*

  lint:
    <<: *defaults
    steps:
      - attach_workspace:
          at: ~/repo
      - run: echo "npm run lint"

  test:
    <<: *defaults
    steps:
      - attach_workspace:
          at: ~/repo
      - run: echo "npm run test"

  deploy-staging:
    <<: *defaults
    environment:
      NODE_ENV: staging
    steps:
      - attach_workspace:
          at: ~/repo
      - run: npm run generate && npm run deploy

  deploy-production:
    <<: *defaults
    environment:
      NODE_ENV: production
    steps:
      - attach_workspace:
          at: ~/repo
      - run: npm run generate && npm run deploy

workflows:
  version: 2
  release:
    jobs:
      - setup
      - lint:
          requires:
            - setup
      - test:
          requires:
            - setup
      - deploy-staging:
          requires:
            - setup
            - lint
            - test
          filters:
            branches:
              only: staging
